- name: Systemd reload
  systemd:
    daemon_reload: yes

- name: prometheus service restart
  systemd:
    name: prometheus
    state: restarted

- name: alertmanager service restart
  systemd:
    name: alertmanager
    state: restarted