# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "CMS" do |vmconfig| 
   vmconfig.vm.box = 'bento/ubuntu-22.04'
   vmconfig.vm.hostname = 'CMS'
   vmconfig.vm.network :private_network, ip: "10.0.0.41"
   vmconfig.vm.network "forwarded_port", guest: 80, host: 8080
   vmconfig.vm.provider "virtualbox" do |vbx|
    vbx.memory = "1024"
    vbx.cpus = "1"
    vbx.customize ["modifyvm", :id, '--audio', 'none']
   end
  end

  config.vm.define "Monitoring" do |vmconfig| 
    vmconfig.vm.box = 'bento/ubuntu-22.04'
    vmconfig.vm.hostname = 'Monitoring'
    vmconfig.vm.network :private_network, ip: "10.0.0.42"
    vmconfig.vm.network "forwarded_port", guest: 9090, host: 9090
    vmconfig.vm.network "forwarded_port", guest: 9093, host: 9093
    vmconfig.vm.provider "virtualbox" do |vbx|
     vbx.memory = "1024"
     vbx.cpus = "1"
     vbx.customize ["modifyvm", :id, '--audio', 'none']
    end
   end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
    ansible.inventory_path = "./inventory/all.yml"
  end 

end
