---
- name: create user prometheus
  user:
    name: prometheus
    create_home: no
    shell: /usr/sbin/nologin
    system: yes

- name: download and extract Prometheus ver.{{ prometheus_version }}
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp
    creates: /tmp/prometheus-{{ prometheus_version }}.linux-amd64
    remote_src: yes

- name: create working directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - '/etc/prometheus'
    - '/var/lib/prometheus'

- name: copy files from temp folder
  copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item.name }}
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop:
    - name: 'prometheus'
      dest: '/usr/local/bin/'
    - name: 'promtool'
      dest: '/usr/local/bin/'
    - name: 'console_libraries'
      dest: '/etc/prometheus/'
    - name: 'consoles'
      dest: '/etc/prometheus/'

- name: create Prometheus configuration files
  template:
    src: templates/prometheus.yml
    dest: /etc/prometheus/

- name: copy systemd service file
  template:
    src: files/prometheus.service
    dest: /etc/systemd/system/
  notify:
    - Systemd reload

- name: prometheus service start and enable
  systemd:
    name: prometheus
    state: started
    enabled: yes
