global:
route:
  group_by: ['alertname']
  group_wait: 1m
  group_interval: 3m
  repeat_interval: 1h
  receiver: 'team-telegram'
  routes:
    - receiver: 'team-telegram'
receivers:
  - name: 'team-telegram'
    telegram_configs:
      - bot_token: {{ lookup('env', 'BOT_TOKEN') }}
        chat_id: {{ lookup('env', 'BOT_CHAT_ID') }}       
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
